[colors]
# https://github.com/alacritty/alacritty-theme/blob/master/themes/onedark.toml
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.normal]
black = "#1e2127"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.bright]
black = "#5b5e64"
blue = "#80ceff"
cyan = "#75d5e1"
green = "#b7e298"
magenta = "#e597fc"
red = "#ff8b94"
white = "#cad1de"
yellow = "#f0b985"

[colors.footer_bar]
background = "#abb2bf"
foreground = "#282c34"

[colors.hints.start]
background = "#d19a66"
foreground = "CellBackground"

[colors.hints.end]
background = "#61afef"
foreground = "CellBackground"

[colors.search.focused_match]
background = "#d19a66"
foreground = "CellBackground"

[colors.search.matches]
background = "#ebd09c"
foreground = "CellBackground"

[font]
size = 11.5

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[hints.enabled]]
regex = """
(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)\
[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
command = "xdg-open"
post_processing = true
binding = { key = "U", mods = "Control|Shift" }
mouse = { enabled = true, mods = "Control" }

[keyboard]
bindings = [
    # Pass `Alt + <key>` as `ESC + <key>`
    { key = "A", mods = "Alt", chars = "\u001Ba" },
    { key = "B", mods = "Alt", chars = "\u001Bb" },
    { key = "C", mods = "Alt", chars = "\u001Bc" },
    { key = "D", mods = "Alt", chars = "\u001Bd" },
    { key = "E", mods = "Alt", chars = "\u001Be" },
    { key = "F", mods = "Alt", chars = "\u001Bf" },
    { key = "G", mods = "Alt", chars = "\u001Bg" },
    { key = "H", mods = "Alt", chars = "\u001Bh" },
    { key = "I", mods = "Alt", chars = "\u001Bi" },
    { key = "J", mods = "Alt", chars = "\u001Bj" },
    { key = "K", mods = "Alt", chars = "\u001Bk" },
    { key = "L", mods = "Alt", chars = "\u001Bl" },
    { key = "M", mods = "Alt", chars = "\u001Bm" },
    { key = "N", mods = "Alt", chars = "\u001Bn" },
    { key = "O", mods = "Alt", chars = "\u001Bo" },
    { key = "P", mods = "Alt", chars = "\u001Bp" },
    { key = "Q", mods = "Alt", chars = "\u001Bq" },
    { key = "R", mods = "Alt", chars = "\u001Br" },
    { key = "S", mods = "Alt", chars = "\u001Bs" },
    { key = "T", mods = "Alt", chars = "\u001Bt" },
    { key = "U", mods = "Alt", chars = "\u001Bu" },
    { key = "V", mods = "Alt", chars = "\u001Bv" },
    { key = "W", mods = "Alt", chars = "\u001Bw" },
    { key = "X", mods = "Alt", chars = "\u001Bx" },
    { key = "Y", mods = "Alt", chars = "\u001By" },
    { key = "Z", mods = "Alt", chars = "\u001Bz" },
]
