[colors]
# https://github.com/sainnhe/edge/

[colors.footer_bar]
background = "#c5cdd9" # fg
foreground = "#2c2e34" # bg0

[colors.hints.start]
background = "#deb974" # yellow
foreground = "CellBackground"

[colors.hints.end]
background = "#6cb6eb" # blue
foreground = "CellBackground"

[colors.normal]
black = "#202023" # black
blue = "#6cb6eb" # blue
cyan = "#5dbbc1" # cyan
green = "#a0c980" # green
magenta = "#d38aea" # purple
red = "#ec7279" # red
white = "#c5cdd9" # fg
yellow = "#deb974" # yellow

[colors.primary]
background = "#2c2e34" # bg0
foreground = "#c5cdd9" # fg

[colors.search.focused_match]
background = "#deb974" # yellow
foreground = "CellBackground"

[colors.search.matches]
background = "#4e432f" # diff_yellow
foreground = "CellForeground"

[font]
size = 11.5

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[hints.enabled]]
regex = """
(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)\
[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
command = "xdg-open"
post_processing = true
binding = { key = "U", mods = "Control|Shift" }
mouse = { enabled = true, mods = "Control" }

[keyboard]
bindings = [
    # Pass `Alt + <key>` as `ESC + <key>`
    { key = "A", mods = "Alt", chars = "\u001Ba" },
    { key = "B", mods = "Alt", chars = "\u001Bb" },
    { key = "C", mods = "Alt", chars = "\u001Bc" },
    { key = "D", mods = "Alt", chars = "\u001Bd" },
    { key = "E", mods = "Alt", chars = "\u001Be" },
    { key = "F", mods = "Alt", chars = "\u001Bf" },
    { key = "G", mods = "Alt", chars = "\u001Bg" },
    { key = "H", mods = "Alt", chars = "\u001Bh" },
    { key = "I", mods = "Alt", chars = "\u001Bi" },
    { key = "J", mods = "Alt", chars = "\u001Bj" },
    { key = "K", mods = "Alt", chars = "\u001Bk" },
    { key = "L", mods = "Alt", chars = "\u001Bl" },
    { key = "M", mods = "Alt", chars = "\u001Bm" },
    { key = "N", mods = "Alt", chars = "\u001Bn" },
    { key = "O", mods = "Alt", chars = "\u001Bo" },
    { key = "P", mods = "Alt", chars = "\u001Bp" },
    { key = "Q", mods = "Alt", chars = "\u001Bq" },
    { key = "R", mods = "Alt", chars = "\u001Br" },
    { key = "S", mods = "Alt", chars = "\u001Bs" },
    { key = "T", mods = "Alt", chars = "\u001Bt" },
    { key = "U", mods = "Alt", chars = "\u001Bu" },
    { key = "V", mods = "Alt", chars = "\u001Bv" },
    { key = "W", mods = "Alt", chars = "\u001Bw" },
    { key = "X", mods = "Alt", chars = "\u001Bx" },
    { key = "Y", mods = "Alt", chars = "\u001By" },
    { key = "Z", mods = "Alt", chars = "\u001Bz" },
]
