#!/usr/bin/env zsh
# Send some notifications with dunst to see how they look

set -euo pipefail

PS4="+> "
set -x

for i in 0 2 1; do
    dunstify -t 0 -u $i -a "Test app" "Summary" "Notification content"
done

dunstify -t 0 -u 1 -a "Test app" "Now with icons" "This one has an icon!!!" \
    -i audio-volume-medium-symbolic
