[package]
name = "ndf"
version = "0.0.0"
edition = "2024"

[dependencies]
anstream = "0.6.18"
anstyle = "1.0.10"
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
