#!/usr/bin/env bash
# Build the NixOS configuration for the current host

set -euo pipefail

PS4='+> '
set -x

nix build \
    "git+file://${CONFIG_REPO_ROOT}#nixosConfigurations.${HOSTNAME}.config.system.build.toplevel" \
    --no-link \
    "$@"
