#!/usr/bin/env bash
# Run `nixos-rebuild build`

set -euo pipefail


tmp_dir=$(mktemp --directory --tmpdir nixos-rebuild-build.XXXXXXXXXX)
trap 'rm -rf "${tmp_dir}"' EXIT

(
    cd "${tmp_dir}"
    PS4='+> '
    set -x
    nixos-rebuild build --flake "${CONFIG_REPO_ROOT}" "$@"
)
