#!/usr/bin/env bash
# Run home-manager for the current home configuration

set -euo pipefail

user=$(id -un)
host=$(uname -n)

PS4="+> "
set -x

nix run "$CONFIG_REPO_ROOT#home-manager" -- --flake "$CONFIG_REPO_ROOT#$user@$host" "$@"
