#!/usr/bin/env bash
# Bump version of doom emacs

set -euo pipefail

version_file="$LINUX_CONFIG_ROOT/emacs/doom/doom-version"
old=$(<"$version_file")
new=$(git ls-remote https://github.com/doomemacs/doomemacs.git HEAD | cut -f 1)
echo "$new" > "$version_file"

echo "Doom: $old -> $new"
