#!/usr/bin/env bash
# Build all packages and nixos configurations of a flake

set -euo pipefail

system=$(nix eval --impure --raw --expr 'builtins.currentSystem')
flake=$(nix flake show --json)

function get_packages () {
    echo "$flake" | jq --raw-output --arg system "$system" '
        .packages[$system] // {} | keys | .[] |
         ".#\(.)"
    '
}

packages=$(get_packages)

function get_nixos_systems () {
    echo "$flake" | jq --raw-output '
        .nixosConfigurations // {} | keys | .[] |
        ".#nixosConfigurations.\(.).config.system.build.toplevel"
    '
}

nixos_systems=$(get_nixos_systems)

PS4='+> '
set -x

nix build $packages $nixos_systems "$@"
