#!/usr/bin/env bash
# Bump versions of nixpkgs and other nix dependencies

set -euo pipefail

function trace_cmd () {
    echo "+>" "$@"
    "$@"
}

function get_deps () {
    nix flake metadata path:. --json | jq '.locks.nodes | with_entries(
        select(.key != "root")
        | {key, value: .value.locked | {lastModified, narHash}}
    )'
}

function diff_deps () {
    echo "$1" "$2" | jq --slurp --raw-output '. as [$old, $new] |
        ($old + $new) | keys |
        map(select($old[.].narHash != $new[.].narHash)) |
        def fmt_date: if . == null
            then "null"
            else (.lastModified | gmtime | strftime("%Y-%m-%d"))
        end;
        map("- \(.): " + ($old[.] | fmt_date) + " -> " + ($new[.] | fmt_date)) |
        join("\n")
    '
}

commit_msg_header="[Nix] Update flake inputs

"

cd "${LINUX_CONFIG_ROOT}"

old=$(get_deps)

trace_cmd nix flake update

new=$(get_deps)
diff=$(diff_deps "${old}" "${new}")

if [ -n "$diff" ]; then
    trace_cmd git add flake.lock

    echo "+>" git commit -m ...
    git commit -m "${commit_msg_header}${diff}"
fi
